export const days = [
  { day: 1, screen: 'onboarding' },
  { day: 2, screen: 'markdown' },
  { day: 3, screen: 'splash-screen' },
  { day: 4, screen: 'airbnb-map' },
  { day: 5, screen: 'tinder-swipe' },
  { day: 6, screen: 'voice-memos' },
  { day: 7, screen: '' },
  { day: 8, screen: '' },
  { day: 9, screen: '' },
  { day: 10, screen: '' },
  { day: 11, screen: '' },
  { day: 12, screen: '' },
  { day: 13, screen: '' },
  { day: 14, screen: '' },
  { day: 15, screen: '' },
  { day: 16, screen: '' },
  { day: 17, screen: '' },
  { day: 18, screen: '' },
  { day: 19, screen: '' },
  { day: 20, screen: '' },
  { day: 21, screen: '' },
  { day: 22, screen: '' },
  { day: 23, screen: '' },
  { day: 24, screen: '' },
];
